mail_pro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('send_mail.urls', namespace='send_mail')),
]

send_mail/urls.py
from django.urls import path
from send_mail import views

app_name = 'send_mail'

urlpatterns = [
    path('', views.home, name='send_test'),
]

send_mail/models.py
from django.db import models

# Create your models here.

send_mail/forms.py
from django import forms

class SendForm(forms.Form):
    email = forms.EmailField(label="Email", max_length=100)
    content = forms.CharField(label="Content", max_length=200)

send_mail/views.py
import os
from django.http import HttpResponse
from django.shortcuts import render

from .forms import SendForm
from django.core.mail import send_mail, BadHeaderError

def home(request):
    if request.method == "POST":
        form = SendForm(request.POST)
        if form.is_valid():
            subject = 'Message from TestAccount'
            message = form.cleaned_data['content']
            sender = form.cleaned_data['email']
            recipients = os.getenv('TO_EMAIL')
            try:
                send_mail(subject, message, sender, [recipients], fail_silently=False)
                return HttpResponse('Successfully sent a message!')
            except BadHeaderError:
                return HttpResponse('Error!')
    else:
        form = SendForm()
    return render(request, 'send_test/home.html', {'form':form })

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

templates/send_test/home.html
{% extends 'base.html' %}

{% block content %}
    <h1>SendGrid Test App</h1>
    <form id="TestForm" method="post" action="{% url 'send_mail:send_test' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="Test">send message</button>
    </form>
{% endblock %}